crosscomp for win64

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -7,12 +7,12 @@ SDL2_IMAGE="SDL2_image-2.0.1"
 TRASHFILE="TRASHFILE.trash"
 NLFBUILDPATH="BINARIES"
 WINSTUFF="4windows"
-SDL2_WIN32="$WINSTUFF/SDL2-2.0.4-win32-x86.zip"
-SDL2_WIN64="$WINSTUFF/SDL2-2.0.4-win32-x64.zip"
-SDL2_IMAGE_WIN32="$WINSTUFF/SDL2_image-2.0.1-win32-x86.zip"
-SDL2_IMAGE_WIN64="$WINSTUFF/SDL2_image-2.0.1-win32-x64.zip"
+SDL2_WIN_file="SDL2-devel-2.0.4-mingw.tar.gz"
+SDL2_WIN="SDL2-2.0.4"
+SDL2_IMAGE_WIN_file="SDL2_image-devel-2.0.1-mingw.tar.gz"
+SDL2_IMAGE_WIN="SDL2_image-2.0.1"
 
-## CHECKING SOURCE FILE EXISTENCE##
+## CHECKING SOURCE FILE EXISTENCE
 if ! [ -e "$ThirdSRC/$LUA.tar.gz" ]; then
 	echo "lua source '$ThirdSRC/$LUA.tar.gz' not found"
 	echo "Aborting..."
@@ -31,26 +31,14 @@ if ! [ -e "$ThirdSRC/$SDL2_IMAGE.tar.gz" ]; then
 	exit 1
 fi
 
-if ! [ -e "$ThirdSRC/$SDL2_WIN32" ]; then
-	echo "SDL2 lib for WIN32 '$ThirdSRC/$SDL2_WIN32' not found"
+if ! [ -e "$ThirdSRC/$WINSTUFF/$SDL2_WIN_file" ]; then
+	echo "SDL2 lib for WIN '$ThirdSRC/$WINSTUFF/$SDL2_WIN_file' not found"
 	echo "Aborting..."
 	exit 1
 fi
 
-if ! [ -e "$ThirdSRC/$SDL2_WIN64" ]; then
-	echo "SDL2 lib for WIN64'$ThirdSRC/$SDL2_WIN64' not found"
-	echo "Aborting..."
-	exit 1
-fi
-
-if ! [ -e "$ThirdSRC/$SDL2_IMAGE_WIN32" ]; then
-	echo "SDL2_IMAGE lib for WIN '$ThirdSRC/$SDL2_IMAGE_WIN32' not found"
-	echo "Aborting..."
-	exit 1
-fi
-
-if ! [ -e "$ThirdSRC/$SDL2_IMAGE_WIN64" ]; then
-	echo "SDL2_IMAGE lib for WIN '$ThirdSRC/$SDL2_IMAGE_WIN64' not found"
+if ! [ -e "$ThirdSRC/$WINSTUFF/$SDL2_IMAGE_WIN_file" ]; then
+	echo "SDL2_IMAGE lib for WIN '$ThirdSRC/$WINSTUFF/$SDL2_IMAGE_WIN_file' not found"
 	echo "Aborting..."
 	exit 1
 fi
@@ -61,41 +49,6 @@ if ! [ -d "$NLFBUILDPATH" ]; then
 	echo "'$NLFBUILDPATH/' path not found. Created."
 fi
 
-if ! [ -d "$NLFBUILDPATH/$WINSTUFF" ]; then
-	mkdir $NLFBUILDPATH/$WINSTUFF
-	echo "'$NLFBUILDPATH/$WINSTUFF/' path not found. Created."
-fi
-
-if ! [ -d "$NLFBUILDPATH/$WINSTUFF/SDL2" ]; then
-	mkdir $NLFBUILDPATH/$WINSTUFF/SDL2
-	echo "'$NLFBUILDPATH/$WINSTUFF/SDL2/' path not found. Created."
-fi
-
-if ! [ -d "$NLFBUILDPATH/$WINSTUFF/SDL2/32" ]; then
-	mkdir $NLFBUILDPATH/$WINSTUFF/SDL2/32
-	echo "'$NLFBUILDPATH/$WINSTUFF/SDL2/32/' path not found. Created."
-fi
-
-if ! [ -d "$NLFBUILDPATH/$WINSTUFF/SDL2/64" ]; then
-	mkdir $NLFBUILDPATH/$WINSTUFF/SDL2/64
-	echo "'$NLFBUILDPATH/$WINSTUFF/SDL2/64/' path not found. Created."
-fi
-
-if ! [ -d "$NLFBUILDPATH/$WINSTUFF/SDL2_image" ]; then
-	mkdir $NLFBUILDPATH/$WINSTUFF/SDL2_image
-	echo "'$NLFBUILDPATH/$WINSTUFF/SDL2_image/' path not found. Created."
-fi
-
-if ! [ -d "$NLFBUILDPATH/$WINSTUFF/SDL2_image/32" ]; then
-	mkdir $NLFBUILDPATH/$WINSTUFF/SDL2_image/32
-	echo "'$NLFBUILDPATH/$WINSTUFF/SDL2_image/32/' path not found. Created."
-fi
-
-if ! [ -d "$NLFBUILDPATH/$WINSTUFF/SDL2_image/64" ]; then
-	mkdir $NLFBUILDPATH/$WINSTUFF/SDL2_image/64
-	echo "'$NLFBUILDPATH/$WINSTUFF/SDL2_image/64/' path not found. Created."
-fi
-
 
 ## CHECKING FOR REQUIRED COMMAND
 if ! hash tar; then
@@ -103,13 +56,6 @@ if ! hash tar; then
 	sudo apt-get install tar
 else
 	echo "'tar' command is present"
-fi
-
-if ! hash unzip; then
-	echo "'unzip' command found, installing..."
-	sudo apt-get install unzip
-else
-	echo "'unzip' command is present"
 fi
 
 if (! hash g++) || (! hash gcc); then
@@ -122,10 +68,10 @@ else
 fi
 
 
-# COMPILING DEPENDENCIES
+## COMPILING DEPENDENCIES
 printf "\n\nCompiling dependencies...\n"
 
-##LUA MAKING
+## LUA MAKING
 cd $ThirdSRC/
 sudo apt-get install libreadline-dev
 tar -zvxf "$LUA.tar.gz" > $TRASHFILE
@@ -137,7 +83,7 @@ mv "lua/" "../../"
 cd ../
 rm -r $LUA
 
-##SDL2 MAKING
+## SDL2 MAKING
 tar -zvxf "$SDL2.tar.gz" > $TRASHFILE
 sudo apt-get install libsdl-dev libxext-dev
 cd $SDL2/
@@ -153,7 +99,7 @@ mv "include/" "../../SDL2/"
 cd ../
 rm -r $SDL2
 
-##SDL2_image MAKING
+## SDL2_image MAKING
 tar -zvxf "$SDL2_IMAGE.tar.gz" > $TRASHFILE
 sudo apt-get install libsdl2-gfx-1.0-0 libsdl2-gfx-dbg libsdl2-gfx-dev libsdl2-gfx-doc libsdl2-image-dbg libsdl2-image-dev libsdl2-mixer-dbg libsdl2-mixer-dev libsdl2-net-dbg libsdl2-net-dev libsdl2-ttf-dbg libsdl2-ttf-dev libsdl2-2.0-0 libsdl2-dbg libsdl2-dev libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-net-2.0-0 libsdl2-ttf-2.0-0
 sudo apt-get install libxml2-dev libpng12-dev libjpeg8-dev libwebp-dev libtiff5-dev
@@ -167,21 +113,30 @@ mv "SDL_image/" "../SDL2/"
 rm $TRASHFILE
 cd ../
 
-##LIB INSTALLING
+## LIB INSTALLING
 mkdir "SDL2/lib/"
 cp /usr/local/lib/*SDL2* "SDL2/lib/"
 
 
-echo "unpacking libs for windows crosscompilation"
-#LINUX TO WINDOWS LIB CROSSCOMPILING INSTALLING
-unzip $ThirdSRC/$SDL2_WIN32 -d $NLFBUILDPATH/$WINSTUFF/SDL2/32 > $TRASHFILE
-rm $NLFBUILDPATH/$WINSTUFF/SDL2/32/*.txt
-unzip $ThirdSRC/$SDL2_WIN64 -d $NLFBUILDPATH/$WINSTUFF/SDL2/64 > $TRASHFILE
-rm $NLFBUILDPATH/$WINSTUFF/SDL2/64/*.txt
-unzip $ThirdSRC/$SDL2_IMAGE_WIN32 -d $NLFBUILDPATH/$WINSTUFF/SDL2_image/32 > $TRASHFILE
-rm $NLFBUILDPATH/$WINSTUFF/SDL2_image/32/*.txt
-unzip $ThirdSRC/$SDL2_IMAGE_WIN64 -d $NLFBUILDPATH/$WINSTUFF/SDL2_image/64 > $TRASHFILE
-rm $NLFBUILDPATH/$WINSTUFF/SDL2_image/64/*.txt
+## LINUX TO WINDOWS LIB CROSSCOMPILING INSTALLING
+echo "configuring crosscompilation for windows"
+sudo apt-get install mingw-w64
+mkdir "SDL2/$WINSTUFF"
+mkdir  "SDL2/$WINSTUFF/SDL2"
+mkdir  "SDL2/$WINSTUFF/SDL2/64"
+mkdir  "SDL2/$WINSTUFF/SDL2/64/bin"
+mkdir  "SDL2/$WINSTUFF/SDL2_image"
+mkdir  "SDL2/$WINSTUFF/SDL2_image/64"
+mkdir  "SDL2/$WINSTUFF/SDL2_image/64/bin"
+tar -zvxf "$ThirdSRC/$WINSTUFF/$SDL2_WIN_file" > $TRASHFILE
+mv $SDL2_WIN/i686-w64-mingw32/lib/*.a SDL2/4windows/SDL2/64
+mv $SDL2_WIN/lib/x64/*.lib SDL2/4windows/SDL2/64
+mv $SDL2_WIN/lib/x64/*.dll SDL2/4windows/SDL2/64/bin
+rm -R $SDL2_WIN
+tar -zvxf "$ThirdSRC/$WINSTUFF/$SDL2_IMAGE_WIN_file" > $TRASHFILE
+mv $SDL2_IMAGE_WIN/i686-w64-mingw32/lib/*.a SDL2/4windows/SDL2_image/64
+mv $SDL2_IMAGE_WIN/i686-w64-mingw32/bin/*.dll SDL2/4windows/SDL2_image/64/bin
+rm -R $SDL2_IMAGE_WIN
 rm $TRASHFILE
 
 echo "*done*"
